# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 12:19
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('entry_in_out', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='student_name',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='studies',
            old_name='subject_name',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='student',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(default=datetime.datetime(1993, 1, 2, 0, 0)),
        ),
        migrations.AddField(
            model_name='student',
            name='image1',
            field=models.ImageField(default='no-image.png', upload_to='images'),
        ),
        migrations.AddField(
            model_name='student',
            name='image2',
            field=models.ImageField(default='no-image.png', upload_to='images'),
        ),
        migrations.AddField(
            model_name='student',
            name='image3',
            field=models.ImageField(default='no-image.png', upload_to='images'),
        ),
        migrations.AddField(
            model_name='student',
            name='image4',
            field=models.ImageField(default='no-image.png', upload_to='images'),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='rollno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studies',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='added_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='teacher',
            name='password',
            field=models.CharField(default='123456', max_length=20),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(default='BTECH (Computer Engineering)', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.PositiveSmallIntegerField(default=2016),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='logs',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panels.Student'),
        ),
        migrations.AddField(
            model_name='logs',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panels.Subject'),
        ),
    ]
